<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>workshopos-web-foundation</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WorkshopOS.Application\WorkshopOS.Application.csproj" />
    <ProjectReference Include="..\WorkshopOS.Domain\WorkshopOS.Domain.csproj" />
    <ProjectReference Include="..\WorkshopOS.Infrastructure\WorkshopOS.Infrastructure.csproj" />
  </ItemGroup>

</Project>
